# Generated by Django 4.2.1 on 2024-03-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0004_alter_tweet_image_tweetlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetlike',
            name='is_dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweetlike',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
