# Generated by Django 4.2.1 on 2024-03-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0006_alter_tweet_tweet_alter_tweetreply_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TL', 'Tweet Like'), ('CM', 'Chat Message'), ('F', 'Follow')], max_length=5),
        ),
    ]
