# Generated by Django 4.2.1 on 2025-01-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0007_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
