# Generated by Django 4.2.1 on 2023-08-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_sample_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_1',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
